name: JSON Syntax and Escape Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  json-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install jq, jsonlint and Prettier
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          npm install --save-dev prettier
          npm install -g jsonlint

      - name: JSON Syntax and Structure Check
        run: |
          # Check JSON syntax with jsonlint
          find . -name "*.json" -print0 | xargs -0 jsonlint -q

      - name: JSON Escape and Format Validation
        run: |
          # Check for valid JSON format, including escaping issues, with jq
          for file in $(find . -name "*.json"); do
            if ! jq empty "$file"; then
              echo "JSON format error in $file"
              exit 1
            fi
          done

      - name: Format JSON Files
        run: |
          # Use Prettier to format JSON files in the root directory, excluding package-lock.json and package.json
          npx prettier --write . --tab-width 2

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add *.json
          git reset package.json package-lock.json
          git commit -m "Format JSON files with Prettier"
          git push origin HEAD:${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
